### ISSUE TITLE
'Quiter' logging?

### ISSUE THREAD

**Issue by bjones6** [mllrsohn/gulp-protractor#68] opened 2015-06-28 06:19 UTC
Hey there, just came to ask if theirs an easy way to limit the logging in the console, it's a little verbose for my tastes and most of it has nothing to do with my tests!

Thanks for the great plug-in,

Ben

**Comment by mattfritz** [comment] 2015-12-01 17:30
I'm not sure which output you'd like suppressed, but if you give an example I can probably take a look.

Closing this for now since the issue is so old. Let me know and I'll reopen if necessary

**Closed by mattfritz** 2015-12-01 17:30 UTC
